image: dylanops/php:7.4

variables:
  COMPOSER_USER: cbb842dfe5c6b13a5e82ee3736e43f22
  COMPOSER_PASSWD: a3cd6560594ddfb6302579621b75ff88

before_script:
  - echo $COMPOSER_USER
  - composer config http-basic.repo.magento.com $COMPOSER_USER $COMPOSER_PASSWD
  - composer install

stages:
  - test

executing-test:
  stage: test
  script:
    - vendor/bin/phpcs --standard=Magento2 app/code
  artifacts:
    when: always
    paths:
      - ./reports
    expire_in: 1 week