image: dylanops/php:7.4

before_script:
  - composer install

stages:
  - test

executing-test:
  stage: test
  script:
    - ./vendor/bin/php-cs-fixer --config=.php_cs.dist fix app/code
  artifacts:
    when: always
    paths:
      - ./reports
    expire_in: 1 week