image: dylanops/php:7.4

variables:
  COMPOSER_USER: cbb842dfe5c6b13a5e82ee3736e43f22
  COMPOSER_PASSWD: a3cd6560594ddfb6302579621b75ff88

before_script:
  - composer config http-basic.repo.magento.com $COMPOSER_USER $COMPOSER_PASSWD
  - composer install

stages:
  - build
  - check-quality

executing-build:
  stage: build
  script:
    - php bin/magento module:enable --all
    - php bin/magento setup:di:compile

executing-check-quality:
  stage: check-quality
  script:
    - vendor/bin/phpcs -n --standard=dev/tests/static/framework/Magento app/code
    - vendor/bin/phpmd app/code/ text .phpmd.xml
    - vendor/bin/phpstan analyse --level=8 --configuration=.phpstan.neon app/code
